import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  // ─── Users ───────────────────────────────────────────────────────────────────
  // Synced from Clerk on first sign-in.
  users: defineTable({
    clerkId: v.string(),           // Clerk user ID (identity.subject)
    email: v.string(),
    name: v.optional(v.string()),
    imageUrl: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_clerk_id", ["clerkId"]),

  // ─── Places ───────────────────────────────────────────────────────────────────
  places: defineTable({
    name: v.string(),
    slug: v.string(),
    ownerUserId: v.id("users"),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_slug", ["slug"])
    .index("by_owner", ["ownerUserId"]),

  // ─── User memberships ─────────────────────────────────────────────────────────
  // Links a user to a place with a role. Owners are also inserted here on creation.
  userMemberships: defineTable({
    userId: v.id("users"),
    placeId: v.id("places"),
    role: v.union(v.literal("viewer"), v.literal("admin"), v.literal("owner")),
    joinedAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_place", ["placeId"])
    .index("by_user_and_place", ["userId", "placeId"]),

  // ─── Groups ───────────────────────────────────────────────────────────────────
  // Optional grouping within a place (e.g. "Pod A Floor 1"). B2B only.
  groups: defineTable({
    placeId: v.id("places"),
    name: v.string(),
    createdAt: v.number(),
  }).index("by_place", ["placeId"]),

  // ─── Machines ─────────────────────────────────────────────────────────────────
  machines: defineTable({
    placeId: v.id("places"),
    groupId: v.optional(v.id("groups")),
    name: v.string(),
    type: v.union(v.literal("washer"), v.literal("dryer")),
    state: v.union(v.literal("off"), v.literal("idle"), v.literal("running")),
    previousState: v.optional(v.union(v.literal("off"), v.literal("idle"), v.literal("running"))),
    lastStateChangeAt: v.number(),
    lastHeartbeatAt: v.number(),
    cycleStartedAt: v.optional(v.number()),
    deviceId: v.optional(v.id("devices")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_place", ["placeId"])
    .index("by_group", ["groupId"])
    .index("by_device", ["deviceId"]),

  // ─── Devices ──────────────────────────────────────────────────────────────────
  // Physical LaundryIQ hardware units. deviceId is the 12-char hex eFuse MAC.
  devices: defineTable({
    deviceId: v.string(),          // 12 uppercase hex chars from eFuse MAC (e.g. A1B2C3D4E5F6)
    type: v.union(v.literal("washer"), v.literal("dryer")),
    hardwareVersion: v.string(),   // e.g. "hall_v1"
    firmwareVersion: v.optional(v.string()),
    machineId: v.optional(v.id("machines")),
    placeId: v.optional(v.id("places")),
    claimedAt: v.optional(v.number()),
    lastSeenAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_device_id", ["deviceId"])
    .index("by_machine", ["machineId"])
    .index("by_place", ["placeId"]),

  // ─── API Keys ─────────────────────────────────────────────────────────────────
  // Per-device API keys hashed with SHA-256 before storage. Never shown to users.
  apiKeys: defineTable({
    deviceId: v.id("devices"),
    keyHash: v.string(),           // SHA-256 hex of the raw "liq_..." key
    createdAt: v.number(),
    revokedAt: v.optional(v.number()),
  }).index("by_device", ["deviceId"]),

  // ─── Pending claims ───────────────────────────────────────────────────────────
  // Created by an admin in the dashboard before the device connects for the first time.
  // Expiry: 30 days. The device polls /claim until it finds a matching pending claim.
  pendingClaims: defineTable({
    deviceId: v.string(),          // 12-char hex device ID entered by admin
    placeId: v.id("places"),
    machineId: v.id("machines"),
    type: v.union(v.literal("washer"), v.literal("dryer")),
    createdAt: v.number(),
    expiresAt: v.number(),         // +30 days from createdAt
  })
    .index("by_device_id", ["deviceId"])
    .index("by_expires_at", ["expiresAt"]),

  // ─── Pending invites ──────────────────────────────────────────────────────────
  // Shareable invite links generated by admins/owners.
  // Expiry: 7 days. Token is a 16-char NanoID.
  pendingInvites: defineTable({
    token: v.string(),             // 16-char NanoID, appears in the invite URL
    placeId: v.id("places"),
    role: v.union(v.literal("viewer"), v.literal("admin")),
    invitedByUserId: v.id("users"),
    email: v.optional(v.string()), // optional tracking email
    createdAt: v.number(),
    expiresAt: v.number(),         // +7 days from createdAt
    usedAt: v.optional(v.number()),
    usedByUserId: v.optional(v.id("users")),
  })
    .index("by_token", ["token"])
    .index("by_place", ["placeId"])
    .index("by_expires_at", ["expiresAt"]),

  // ─── Firmware ─────────────────────────────────────────────────────────────────
  // Records published firmware versions. Updated manually or via CI on release.
  firmware: defineTable({
    version: v.string(),           // semver e.g. "1.2.0"
    hardwareVersion: v.string(),   // matches HARDWARE_VERSION in config.h e.g. "hall_v1"
    downloadUrl: v.string(),       // GitHub Releases binary URL
    releaseNotes: v.optional(v.string()),
    publishedAt: v.number(),
    isLatest: v.boolean(),
  })
    .index("by_hardware", ["hardwareVersion", "isLatest"])
    .index("by_version", ["version"]),

  // ─── Push subscriptions ───────────────────────────────────────────────────────
  // Web Push VAPID subscriptions. One user may have multiple (different devices).
  pushSubscriptions: defineTable({
    userId: v.id("users"),
    endpoint: v.string(),
    p256dh: v.string(),
    auth: v.string(),
    machineId: v.optional(v.id("machines")), // null = global prefs; set = machine-specific
    createdAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_machine", ["machineId"]),
});
